### ISSUE TITLE
Algorithms do not perform as claimed in papers

### ISSUE THREAD

**Issue by viktorasl** [MOEAFramework/MOEAFramework#211]
Hey! I'm doing various algorithms analysis for my Master thesis and trying to come up with something new and improve them. Although I struggle replicating the same performance as analysed algorithms state.
I'm trying to replicate IGD performance metric results.
In example NSGA-III:
<img width="795" alt="screenshot 2018-11-27 at 23 01 26" src="https://user-images.githubusercontent.com/3721061/49112150-b0ce5e00-f29a-11e8-844a-5e91a72e4042.png">
<img width="435" alt="screenshot 2018-11-27 at 23 01 59" src="https://user-images.githubusercontent.com/3721061/49112154-b2982180-f29a-11e8-9802-c13fe26eb1a9.png">
but running tests I do get:
```
Problem: DTLZ2_3
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.05565795076010653
        Median: 0.05674932845549693
        Max: 0.05880780874217265
        Count: 50
        Indifferent: []
Problem: DTLZ2_10
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.1715546107894582
        Median: 0.18110834813589666
        Max: 0.20224200646620447
        Count: 50
        Indifferent: []
Problem: DTLZ3_3
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 4.480702494792335
        Median: 14.903405057143631
        Max: 46.550720613850785
        Count: 50
        Indifferent: []
Problem: DTLZ3_10
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.11916123086583777
        Median: 0.12827817513601547
        Max: 0.1405311407880659
        Count: 50
        Indifferent: []
Problem: WFG6_3
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.06044396116083163
        Median: 0.06897207321271229
        Max: 0.084174537308193
        Count: 50
        Indifferent: []
Problem: WFG6_10
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.24652172969777494
        Median: 0.2742986828059819
        Max: 0.3023638492045271
        Count: 50
        Indifferent: []
Problem: WFG7_3
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.05826484536967883
        Median: 0.06034334043032323
        Max: 0.06275341665684146
        Count: 50
        Indifferent: []
Problem: WFG7_10
NSGAIII:
    InvertedGenerationalDistance: 
        Min: 0.24775387356901768
        Median: 0.26041219345582106
        Max: 0.2931884121512899
        Count: 50
        Indifferent: []
```

The differences are really significant and I'm out of ideas what's the reason. Am I missing something?
I even tried to supply more dense true Pareto front sets but that did not help.
Same problem seems like appear with other algorithms as well.
